### ISSUE TITLE
Results eval screen looks jacked on safari

### ISSUE THREAD

**Issue by atareshawty** [osumb/challenges#185]
Not sure why
![screen shot 2016-09-05 at 2 33 31 pm](https://cloud.githubusercontent.com/assets/3112926/18255249/c18af6dc-7375-11e6-8788-caf44234c9d9.png)

**Comment by btmills** [comment]
Are you using flexbox for layout?

**Comment by atareshawty** [comment]
Yeah

**Comment by atareshawty** [comment]
Is that bad?

**Comment by btmills** [comment]
No, Safari is bad. Flexbox in Safari is still a bit buggy. Pull up the Safari devtools and start messing around with the flex styles there. As long as you stick to the basics (it has particular troubles with flex-wrap, for example) then things should shape up. Lmk if you get stuck.

**Comment by atareshawty** [comment]
But I need flex wrap 😢

**Comment by btmills** [comment]
You might have to find another way...






On Mon, Sep 5, 2016 at 2:46 PM -0400, "Alex Tareshawty" <notifications@github.com> wrote:












But I need flex wrap 😢

**Comment by atareshawty** [comment]
Fixed! PR will be up soon, with some other changes I need to make
