### ISSUE TITLE
Heroku db is different?

### ISSUE THREAD

**Issue by atareshawty** [osumb/challenges#52]

**Comment by atareshawty** [comment]
On my local db, we can run the query
```sql
SELECT * FROM performances WHERE openAt < '2016-06-01T04:56:03.690Z'::date 
ORDER BY openAt desc LIMIT 1;
```
To get the next performance. When we run on Heroku's db with the same data, it doesn't return anything. The performances are there with the correct times, but it doesn't return anything

**Comment by atareshawty** [comment]
@tarebyte ...help? I'm stumped on this one

**Comment by tarebyte** [comment]
@atareshawty there shouldn't be any difference, between the two data sets outside of the time it was created. Unless your literally migrating over the data from dev to prod.

**Comment by atareshawty** [comment]
Idk now, but it's not 'not' broken... @tarebyte
